spring.application.name=e-commerce

# K?t n?i Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/databae_name
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# C?u hình JPA / Hibernate
# update: T? ??ng t?o/s?a b?ng theo code Java (Ch? dùng cho Dev)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# C?u hình Server
server.port=8080